# -*- coding: utf-8 -*-
"""testeo_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LeN4joGsNBqIAZAtV2vzijeoKnWV4c_9
"""

def test_crear_libro():

    libro = Libro(
        "Python",
        "Juan Perez",
        "123",
        2024,
        300
    )

    assert libro.titulo == "Python"
    assert libro.autor == "Juan Perez"
    assert libro.isbn == "123"
    assert libro.paginas == 300


def test_crear_usuario():

    usuario = Usuario(
        "Ana",
        "Gomez",
        "11111111",
        "ana@gmail.com"
    )

    assert usuario.nombre == "Ana"
    assert usuario.apellido == "Gomez"
    assert usuario.dni == "11111111"


def test_agregar_libro():

    biblioteca = Biblioteca()

    cantidad_inicial = len(biblioteca.libros)

    libro = Libro(
        "Libro Test",
        "Autor Test",
        "ISBN001",
        2024,
        150
    )

    biblioteca.agregar_libro(libro)

    assert len(biblioteca.libros) == cantidad_inicial + 1


def test_agregar_usuario():

    biblioteca = Biblioteca()

    cantidad_inicial = len(biblioteca.usuarios)

    usuario = Usuario(
        "Carlos",
        "Lopez",
        "22222222",
        "carlos@gmail.com"
    )

    biblioteca.agregar_usuario(usuario)

    assert len(biblioteca.usuarios) == cantidad_inicial + 1


def test_buscar_libro():

    biblioteca = Biblioteca()

    libro = Libro(
        "Busqueda",
        "Autor",
        "ISBNBUSCAR",
        2024,
        200
    )

    biblioteca.agregar_libro(libro)

    encontrado = biblioteca.buscar_libro("ISBNBUSCAR")

    assert encontrado == libro


def test_buscar_usuario():

    biblioteca = Biblioteca()

    usuario = Usuario(
        "Pedro",
        "Perez",
        "33333333",
        "pedro@gmail.com"
    )

    biblioteca.agregar_usuario(usuario)

    encontrado = biblioteca.buscar_usuario("33333333")

    assert encontrado == usuario


def test_prestar_libro():

    biblioteca = Biblioteca()

    libro = Libro(
        "Prestamo",
        "Autor",
        "ISBNPRESTAMO",
        2024,
        100
    )

    usuario = Usuario(
        "Lucia",
        "Diaz",
        "44444444",
        "lucia@gmail.com"
    )

    biblioteca.agregar_libro(libro)
    biblioteca.agregar_usuario(usuario)

    cantidad_inicial = len(biblioteca.prestamos)

    biblioteca.prestar_libro(
        "ISBNPRESTAMO",
        "44444444"
    )

    assert len(biblioteca.prestamos) == cantidad_inicial + 1


def test_devolver_libro():

    biblioteca = Biblioteca()

    libro = Libro(
        "Devolucion",
        "Autor",
        "ISBNDEV",
        2024,
        250
    )

    usuario = Usuario(
        "Maria",
        "Suarez",
        "55555555",
        "maria@gmail.com"
    )

    biblioteca.agregar_libro(libro)
    biblioteca.agregar_usuario(usuario)

    biblioteca.prestar_libro(
        "ISBNDEV",
        "55555555"
    )

    biblioteca.devolver_libro("ISBNDEV")

    assert biblioteca.prestamos[0].fecha_devolucion is not None


def test_no_prestar_dos_veces():

    biblioteca = Biblioteca()

    libro = Libro(
        "Duplicado",
        "Autor",
        "ISBNDUP",
        2024,
        100
    )

    usuario = Usuario(
        "Jose",
        "Garcia",
        "66666666",
        "jose@gmail.com"
    )

    biblioteca.agregar_libro(libro)
    biblioteca.agregar_usuario(usuario)

    biblioteca.prestar_libro(
        "ISBNDUP",
        "66666666"
    )

    biblioteca.prestar_libro(
        "ISBNDUP",
        "66666666"
    )

    assert len(biblioteca.prestamos) == 1


def test_metaclase():

    cantidad_inicial = MetaRegistro.cantidad_instancias

    Libro(
        "Meta",
        "Autor",
        "ISBNMETA",
        2024,
        100
    )

    assert MetaRegistro.cantidad_instancias == cantidad_inicial + 1


def test_polimorfismo():

    objetos = [
        Libro("A", "B", "1", 2024, 100),
        Usuario("Ana", "Perez", "123", "ana@gmail.com")
    ]

    for objeto in objetos:
        assert hasattr(objeto, "mostrar")


def test_guardado_json():

    biblioteca = Biblioteca()

    cantidad_inicial = len(biblioteca.libros)

    biblioteca.agregar_libro(
        Libro(
            "Persistencia",
            "Autor",
            "ISBNJSON",
            2024,
            100
        )
    )

    nueva_biblioteca = Biblioteca()

    assert len(nueva_biblioteca.libros) >= cantidad_inicial + 1

if __name__ == "__main__":
    menu()